### PR TITLE
JavaKit: Enable imported Java classes as Swift classes by default

### PR DESCRIPTION
**Pull request by DougGregor**
Flip the switch to have Java2Swift generate Swift classes to represent
each imported Java class, and make the (relatively few) adjustments
needed to the JavaKit library to make that work.

Implements issue https://github.com/swiftlang/swift-java/issues/132.

### CODE REVIEW

**Comment by DougGregor** [comment]
Note that most of the logic is https://github.com/swiftlang/swift-java/pull/140. This PR exists to switch the default over to the new mechanism.

**Review by ktoso — APPROVED** [review]

**Comment by lhoward** [comment]
FYI this patch breaks building with Swift 6.0.2 (not Android-specific).

```
error: emit-module command failed with exit code 1 (use -v to see invocation)
macro expansion @JavaStaticField:5:5: error: 'nonmutating' is not valid on setters in classes
`- /Users/lukeh/CVSRoot/apple/swift-java/Samples/JavaKitSampleApp/.build/plugins/outputs/javakitsampleapp/JavaKitExample/destination/Java2SwiftPlugin/generated/HelloSubclass.swift:15:34: note: expanded code originates here
13 | extension JavaClass<HelloSubclass> {
14 |   @JavaStaticField(isFinal: false)
15 |   public var initialValue: Double
   +--- macro expansion @JavaStaticField -------------------------------
   |3 |         self[javaFieldName: "initialValue", fieldType: Double.self]
   |4 |     }
   |5 |     nonmutating set {
   |  |     `- error: 'nonmutating' is not valid on setters in classes
   |6 |         self[javaFieldName: "initialValue", fieldType: Double.self] = newValue
   |7 |     }
   +--------------------------------------------------------------------
16 | }
17 | 
````

**Comment by DougGregor** [comment]
Sorry, must be that we aren't building this sample in CI yet. Fix here: https://github.com/swiftlang/swift-java/pull/146

**Comment by DougGregor** [comment]
@lhoward should be fixed on main now

**Comment by lhoward** [comment]
Thanks, works.

**Comment by lhoward** [comment]
Think there may be some rough edges with return type overloading.

```
% grep array *
JavaNIOBuffer.swift:  open func array() -> JavaObject!
JavaNIOBuffer.swift:  open func arrayOffset() -> Int32
JavaNIOByteBuffer.swift:  open override func array() -> [Int8]
JavaNIOByteBuffer.swift:  open override func arrayOffset() -> Int32
```

```
/Users/lukeh/CVSRoot/padl/inferno/ui/FlutterSwift/.build/plugins/outputs/flutterswift/AndroidFlutter/destination/Java2SwiftPlugin/generated/JavaNIOBuffer.swift:35:13: note: potential overridden instance method 'array()' here
33 | 
34 |   @JavaMethod
35 |   open func array() -> JavaObject!
   |             `- note: potential overridden instance method 'array()' here
36 | 
37 |   @JavaMethod
/Users/lukeh/CVSRoot/padl/inferno/ui/FlutterSwift/.build/plugins/outputs/flutterswift/AndroidFlutter/destination/Java2SwiftPlugin/generated/JavaNIOByteBuffer.swift:158:22: error: method does not override any method from its superclass
156 | 
157 |   @JavaMethod
158 |   open override func array() -> [Int8]
    |                      `- error: method does not override any method from its superclass
159 | 
160 |   @JavaMethod

/Users/lukeh/CVSRoot/padl/inferno/ui/FlutterSwift/.build/plugins/outputs/flutterswift/AndroidFlutter/destination/Java2SwiftPlugin/generated/JavaNIOBuffer.swift:35:13: note: potential overridden instance method 'array()' here
```

**Comment by DougGregor** [comment]
Fix for the (non-)covariance of array-returning methods at https://github.com/swiftlang/swift-java/pull/148

**Pull request merged**
