### PR TITLE
build: add proper search path for Windows

### PR DESCRIPTION
**Pull request by compnerd**
The Windows includes are under `win32` at least with the Oracle JDK. This is required to be able to build on Windows.

### CODE REVIEW

**Comment by ktoso** [comment]
Thanks for the fix, there's probably some `/` vs `\` laying around as well.

Thanks!

**Comment by ktoso** [comment]
We don't do Windows CI yet but we could soon

**Comment by compnerd** [comment]
Yes, I'm planning on continuing some additional work here for exposing Java to Swift.

**Comment by ktoso** [comment]
Ok, awesome! Let's get the repo into shape to support windows then :-) 

Sorry for the delay, I'll get CI green tomorrow and merge all such pending PRs. Since we use nightly toolchain it regressed us accidentally

**Review by DougGregor — APPROVED** [review]
LGTM.

**Comment by ktoso** [comment]
Thanks @compnerd!

**Pull request merged**
